# Generated by Django 5.1.6 on 2025-02-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_remove_booking_services_booking_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(to='apiapp.service'),
        ),
    ]
